### ISSUE TITLE
Add OpenFunscripter as media source

### ISSUE THREAD

**Issue by Yoooi0** [Yoooi0/MultiFunPlayer#105]
Api: OpenFunscripter/OFS/issues/59

**Comment by OpenFunscripter** [comment]
If you have suggestions on what this should look like feel free to make them.
I want to get this right the first time and not have breaking changes later down the line. 🙂

Currently I have these [events](https://github.com/OpenFunscripter/OFS/blob/6d8af91a79b67fa9c1409f08ff0e94a0b0096bcc/src/api/OFS_WebsocketApiEvents.cpp).
`project_change` indicates that you have clear everything after which you would receive a chain of events to reinitialize to the new project.

And this [funscript_change](https://github.com/OpenFunscripter/OFS/blob/6d8af91a79b67fa9c1409f08ff0e94a0b0096bcc/src/api/OFS_WebsocketApiClient.cpp#L143) event (which looking at the code should also be defined in the other file).
The axis mapping can only be determined by looking at the name field and checking for the conventional `.roll`, `.sway`,... extensions. 
Note this event still needs an additional identifier because the `name` can change.
So I will add an additional field `index` because the order can't change to uniquely identify the script.

There are no commands yet.

**Comment by Yoooi0** [comment]
Yup, will make any suggestions in your issue to not mix things up 👍 

I had it working very quickly, I just have to make some internal changes in MFP because the axis mapping is done very late now. Probably have to make it a global utility method.
