### ISSUE TITLE
Integration with Stash

### ISSUE THREAD

**Issue by mnh86** [Yoooi0/MultiFunPlayer#117]
**Describe the solution you'd like**

Consider support for Stash as another player option.

Docs: https://docs.stashapp.cc/
Repo: https://github.com/stashapp/stash

An interesting [issue here](https://github.com/stashapp/stash/issues/3031) about implementing a similar t-code interface into Stash. 

Would there be advantages to integrating with MFP itself or a Stash plugin to bridge somehow?

**Comment by Yoooi0** [comment]
I have not checked stash docs (and never used it) but what I would like to happen is for stash to act as a script library (#104) and when video is playing I would like to query stash for a matching script.

Im assuming stash also acts as a media host so you can play videos via dlna or web interface in vr/media players.

> apologies, I just found this possible duplicate: https://github.com/Yoooi0/MultiFunPlayer/issues/103

That issue was about integrating with a third party stash plugin.
I guess this could be merged with #104 but i'll leave it for now.
