### ISSUE TITLE
Keeps asking for .net 5.0.0

### ISSUE THREAD

**Issue by jo111git** [Yoooi0/MultiFunPlayer#12]
Hi!
Thanks for writing this :o)
Every time I try to start it, I get a popup saying i must install .NET
I've followed the link and tried 5.0.0 x86 and 5.0.0 x64 (Windows) and the latest 5.* branch, but none of them stop the popup - it seems to think it isn't installed. I've verified in Add/Remove Programs that .NET Runtime 5.0.0 IS installed. It looks like I must be doing something wrong, but what.......
Thank you.

**Comment by VincentVonDarkness** [comment]
Having the same issue as well. Even Scriptplayer isn't working right. Shuts down if you even try to connect to buttplug.io via Intiface Desktop.

**Comment by Yoooi0** [comment]
@jo111git Sorry for late reply, it seems they split the .net 5.0 downloads into console and desktop, so make sure you install the one under "Run desktop apps". Also when you run MultiFunPlayer, windows itself should show you a prompt that you are missing .net 5.0 and it should install it for you from that popup. And just to be sure restart the pc after installing.

@VincentVonDarkness Same as above I guess. Also Scriptplayer uses the old .net framework 4.6.2 so that issue shouldn't be connected.

You could try [1.14.0](https://github.com/Yoooi0/MultiFunPlayer/releases/tag/1.14.0). It might be possible that some latest windows update broke something.

**Comment by VincentVonDarkness** [comment]
Well I thank you for getting back to me I will do a test run on a vm with .net 4.6.2 for the script player issue, the author never get back to me. I do testing the versions you are telling me about on another vm with the .net 5.0.7 and post back here with links for anyone that runs into this issue.

**Comment by VincentVonDarkness** [comment]
Well I have an Update for everyone that has this issue. [https://versionsof.net/core/5.0/5.0.2/](url) 5.0.2 Runtime for windows Desktop so that you may run this program. Windows Desktop Runtime is what you are looking for. x86 for 32 bit windows x64 for 64 bit Windows. Yes this will work for MultiFunPlayer ver 1.13.1 and the latest realease as well 1.14.0. I hope this helps anyone that needs it.
