### ISSUE TITLE
Funscripts don't work when using XBVR versions later than 0.4.23

### ISSUE THREAD

**Issue by volcanofishing** [Yoooi0/MultiFunPlayer#178]
When viewing videos via XBVR 0.4.24 onwards through Heresphere on a Meta Quest 3 the associated funscripts don't appear to fully load in MultiFunPlayer. The name of the scene appears without ID and the heatmap stays blank.

Using XBVR 0.4.23 everything works as it always has, the script loads with the heatmap and plays correctly.

I know there was a breaking change in XBVR that caused this and I'd generally think it would be fixed at there, however I saw on the XBVR Discord that @Yoooi0 had a PR with a potential fix and it has since been merged.

I didn't put this in Issues because it feels like maybe it's a known just undocumented issue. Just wondering if there's a chance a fix being actively worked on for a future MFP release?

Thanks!

Setup: 
XBVR 0.4.23
Initface Central v2.6.0
MultiFunPlayer v1.30.2 (Patreon Build)
Heresphere 0.11.0

**Comment by Yoooi0** [comment]
I don't think it is possible for HereSphere + XBVR + MFP to work at all, so dunno how you managed 0.4.23 to work.

There were two issues I fixed in XBVR 0.4.26 and 0.4.27.
And HereSphere was sending only the scene title instead of stream url which was fixed in v0.11.0.
The new HereSphere update requires MFP to update so HereSphere + XBVR + MFP should work once v1.30.3 or v1.40.0 is released.
