### ISSUE TITLE
//#r file:<dll> does not load assembly

### ISSUE THREAD

**Issue by jaynopsis** [Yoooi0/MultiFunPlayer#185]
**Describe the bug**
`//#r file:<dll>` correctly adds a reference for compilation, but does not load assembly into memory, which causes a crash. The fix is very simple - https://github.com/Yoooi0/MultiFunPlayer/commit/8b7601c6fe8aa38076d095d2380f02bc2f47fed1

**To Reproduce**
1. Add any file reference, for example: `//#r "file:Microsoft.Windows.SDK.NET.dll"`
2. Use any type from this dll: ` await DeviceInformation.FindAllAsync(GattDeviceService.GetDeviceSelectorFromUuid(GattServiceUuids.HeartRate))`
3. Compile (without error)
4. Run
5. Crash with error: `System.TypeLoadException: Could not resolve type 'MultiFunPlayer.SmartHeartRate.SmartHeartRatePlugin' in assembly 'Plugin_SmartHeartRate, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.`

**Comment by Yoooi0** [comment]
Thanks for bringing this up.
Fixed and also made it so all plugin references are loaded into the plugin AssemblyLoadContext so that they are also unloaded with the plugin.
Will be in v1.31.1 or v1.32.0, not sure if backporting is necessary since im pretty sure you are the only one writing a plugin for MFP.

**Comment by Yoooi0** [comment]
Fixed in v1.31.1.
Also since v1.30.0 the format changed to `//#r "path or name"`, there is no `file:` / `name:`
