### ISSUE TITLE
Unable to load buttplug_rs_ffi.dll

### ISSUE THREAD

**Issue by thorus90** [Yoooi0/MultiFunPlayer#30]
Hi,

I can't start it, I installed .net but no window shows up.
In the Logs I can find this:

2021-11-05 17:14:51.0469|FATAL|AppDomain|System.DllNotFoundException: Unable to load DLL 'buttplug_rs_ffi' or one of its dependencies: Das angegebene Modul wurde nicht gefunden. (0x8007007E)
   at Buttplug.ButtplugFFILogCalls.ButtplugCreateLogHandle(ButtplugLogCallback callback, IntPtr ctx, String level, Boolean aUseJSON)

In the folder there is the buttpluf_rs_ffi.dll but why can it not be found?

**Comment by Yoooi0** [comment]
It wouldnt load on my clean sandbox windows and I was pretty stunned as why it would do that.
Figured out that apparently you also need [Visual C++ x64 2015 runtime](https://www.microsoft.com/en-gb/download/details.aspx?id=48145) installed because buttplug requires it.

I will add it to requirements and maybe figure out if its possible to force windows to prompt if its not installed.

**Comment by Yoooi0** [comment]
Added [lastest](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-160) visual c++ redistributable as a prerequisite in readme, and added a popup in case it is not installed so it does not silently crash.

Thanks for binding this up.
